App:
  Environment: "dev"
  Id: "STLS-ASSESSMENT"
kafka:
  Brokers: ["localhost:9092"]
  TopicsConsumer: ["security-assessment"]
  TopicsProducer: ["security-assessment"]
  GroupID: "security-assessment-ingestion-group"
