App:
  Environment: "dev"
  Id: "STLS-ASSESSMENT"
  PathToResults: "/home/stls/results/"
kafka:
  Brokers: ["kafka1:9092", "kafka2:9092", "kafka3:9092"]
  TopicsConsumer: ["security-assessment"]
  TopicsProducer: ["security-assessment"]
  GroupID: "security-assessment-ingestion-group"
